# Generated by Django 4.1.7 on 2024-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rice',
            field=models.IntegerField(),
        ),
    ]
